---
baseURL: https://thisis.nedpals.xyz/
languageCode: en-us
title: neds blog
theme: hugo-type-theme
disqusShortname: nedpals
paginate: 5
buildDrafts: false
canonifyurls: true
menu:
  nav:
  - name: YouTube
    url: https://youtube.com/dotgeeq
  - name: Patreon
    url: https://patreon.com/dotgeeq
  - name: Portfolio
    url: https://nedpals.xyz
params:
  author: Ned
  copyright: Released under the MIT license<br>Powered by [Hugo](//gohugo.io/) with
    the [Type Theme](//github.com/digitalcraftsman/hugo-type-theme)
  description: tech, tech, and more
  gravatar: npdoesmc@gmail.com
  headertext: ''
  social:
    github: nedpals
    gitlab: nedpals
    homepage: true
    rss: true
    twitter: npned
permalinks:
  post: "/:year/:month/:title/"
sharing:
  twitter: true
  facebook: true
  google-plus: false
  pinterest: false
