baseURL: "https://thisis.nedpals.xyz/"
languageCode: "en-us"
title: "neds blog"
theme: "hugo-type-theme"
disqusShortname: "nedpals"
paginate: 5
buildDrafts: false
canonifyurls: true

permalinks:
  post: /:year/:month/:title/

params:
  description: "tech, tech, and more"
  author: "Ned"
  headerText: "hello world"
  gravatar: "npdoesmc@gmail.com"
  copyright: "Released under the MIT license<br>Powered by [Hugo](//gohugo.io/) with the [Type Theme](//github.com/digitalcraftsman/hugo-type-theme)"

  social:
    rss: true
    homepage: true
    github: "nedpals"
    gitlab: "nedpals"
    twitter: "npned"

sharing:
  twitter: true
  facebook: true
  google-plus: false
  pinterest: false

menu:
  nav:
    - name: "Portfolio"
      url: "https://nedpals.xyz"
    - name: "Patreon"
      url: "https://patreon.com/dotgeeq"
    - name: "YouTube"
      url: "https://youtube.com/dotgeeq"