---
upload_path: "/content/images/uploads"
frontmatter_file_url_template: "/content/uploads/:year:/:month:/:day:"
body_file_url_template: "/content/uploads/:year:/:month:/:day:"
new_page_extension: md
auto_deploy: false
admin_path: admin
webhook_url: 
sections: 
version: 0.31.1
