backend:
  name: github
  repo: nedpals/blog # Path to your GitHub repository
  branch: master # Branch to update (master by default)

media_folder: "content/images/uploads" # Folder where user uploaded files should go
public_folder: "content" # Folder where user uploaded files should go

collections: # A list of collections the CMS should be able to edit
  - name: "post" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Post" # Used in the UI, ie.: "New Post"
    folder: "content/post" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Draft", name: "draft", widget: "boolean", default: "false"}
      - {label: "Category", name: "category", widget: "list" }
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: "Featured Image", name: "featureimage", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "settings"
    label: "Settings"
    editor:
      preview: false
    files:
      - name: "general"
        label: "Site Settings"
        file: "config.yaml"
        description: "General Site Settings"
        fields:
          - { label: "Base URL", name: "baseURL", widget: "string" }
          - { label: "Language Code", name: "languageCode", widget: "string" }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Theme", name: "theme", widget: "string" }
          - { label: "Disqus Shortname", name: "disqusShortname", widget: "string" }
          - { label: "No. of Posts to Paginate", name: "paginate", widget: "number" }
          - { label: "Build drafts?", name: "buildDrafts", widget: "boolean" }
          - { label: "Canonify URLs", name: "Canonifyurls", widget: "boolean" }
