---
label: default
hide_body: false
is_partial: false
fields:
- type: text
  label: Title
  name: title
  config:
    required: true
- type: datetime
  name: date
  label: Date
  config:
    required: true
  default: Invalid date
- type: tag_list
  name: category
  label: Category
- type: tag_list
  name: tags
  label: Tags
- type: file
  label: Featured image
  name: featureimage
pages:
- content/post/domain-is-back-and-a-lesson-to-users-of-paymaya.md
- content/post/importance-of-mil.md
- content/post/site-update-8-3-18.md
- content/post/google-drive-hell.md
- content/post/making-a-manga.md
- content/post/goodbye-bato.to.md
- content/post/code-achievements.md
- content/post/sharn-0.2.0-and-merging-with-shards.md
